name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Many color libraries just need this to be set to any value, but at least
  # one distinguishes color depth, where "3" -> "256-bit color".
  FORCE_COLOR: 3

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual --all-files
      # - name: Run PyLint
      #   run: |
      #     echo "::add-matcher::$GITHUB_WORKSPACE/.github/matchers/pylint.json"
      #     pipx run nox -s pylint

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        runs-on: [ubuntu-latest] # , macos-latest, windows-latest]

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install package
        run: python -m pip install .[test]

      - uses: actions/checkout@v4
        with:
          repository: ChannelFinder/ChannelFinderService
          path: ChannelFinderService
          fetch-depth: 0

      - name: Install package
        run: |
          cp ChannelFinderService/pom.xml .

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Start ChannelFinder server
        run: |
          patch_location=${PWD}/.github/docker-compose.patch
          cd ChannelFinderService
          mvn --version
          mvn install -D skipTests
          patch -u docker-compose.yml -i ${patch_location}
          docker-compose up --build -d
          sleep 30

      # - name: Check ChannelFinder server is accessible
      #   run: |
      #     curl -X 'GET' -k 'https://localhost:8443/ChannelFinder' -H 'accept: */*'

      - name: Test package
        run: >-
          python -m pytest -ra --cov --cov-report=xml --cov-report=term
          --durations=20

      - name: Check docker logs
        run: |
          docker-compose logs channelfinder

      - name: Upload coverage report
        uses: codecov/codecov-action@v4.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
